version: 1
update_configs:
  - package_manager: "javascript"
    directory: '/'
    update_schedule: "live"
    default_reviewers:
      - "nickific"
    default_labels:
      - "security"
    allowed_updates:
      - match:
          update_type: "security"
